export enum HttpStatusCode {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  CONFLICT = 409,
  UNPROCESSABLE_ENTITY = 422,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504
}

export enum AuthStatusCode {
  USER_NOT_AUTHENTICATED = HttpStatusCode.UNAUTHORIZED,
  COMPANY_NOT_AUTHENTICATED = HttpStatusCode.UNAUTHORIZED,
  INSUFFICIENT_PERMISSIONS = HttpStatusCode.FORBIDDEN
}

export enum JobStatusCode {
  JOB_CREATED = HttpStatusCode.CREATED,
  JOB_UPDATED = HttpStatusCode.OK,
  JOB_DELETED = HttpStatusCode.OK,
  JOB_NOT_FOUND = HttpStatusCode.NOT_FOUND,
  
  JOBS_RETRIEVED = HttpStatusCode.OK,
  JOB_RETRIEVED = HttpStatusCode.OK,
  JOBS_SEARCHED = HttpStatusCode.OK,
  
  APPLICATION_SUBMITTED = HttpStatusCode.OK,
  APPLICATION_ALREADY_EXISTS = HttpStatusCode.CONFLICT,
  APPLICATIONS_RETRIEVED = HttpStatusCode.OK,
  
  SUGGESTIONS_RETRIEVED = HttpStatusCode.OK
}

export enum ValidationStatusCode {
  VALIDATION_ERROR = HttpStatusCode.BAD_REQUEST,
  MISSING_REQUIRED_FIELDS = HttpStatusCode.BAD_REQUEST,
  QUERY_PARAMETER_REQUIRED = HttpStatusCode.BAD_REQUEST,
  INVALID_JOB_DATA = HttpStatusCode.UNPROCESSABLE_ENTITY,
  INVALID_SEARCH_FILTERS = HttpStatusCode.UNPROCESSABLE_ENTITY
}

export enum ApplicationStatusCode {
  APPLICATION_SUCCESS = HttpStatusCode.OK,
  DUPLICATE_APPLICATION = HttpStatusCode.CONFLICT,
  APPLICATION_DEADLINE_PASSED = HttpStatusCode.BAD_REQUEST,
  JOB_NOT_AVAILABLE = HttpStatusCode.BAD_REQUEST,
  INSUFFICIENT_QUALIFICATIONS = HttpStatusCode.BAD_REQUEST
}
